### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by mmPaumard** [NicolasBellec/AD4T_site_web#2]
Create a form that send an email containing:
- name
- email
- topic
- message
for the contact page.
(I'll do the design)

**Comment by NicolasBellec** [comment]
Form working, the backend receives the data, check them but doesn't send a mail yet.

**Comment by NicolasBellec** [comment]
Email are sent through a file backend, just have to change the backend, give credential to a smtp server so it can send e-mail.
PS: The redirection page after an email is send are not ready yet (they are just text for now).

**Comment by NicolasBellec** [comment]
Pas d'effacement des labels lors de la saisie de caractères dans les différents champs

**Comment by mmPaumard** [comment]
Done ;) Il manquait une lib ^^'
